# Generated by Django 5.2 on 2025-04-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('data', models.DateField()),
                ('titolo', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Immagini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.BinaryField()),
                ('descrizione', models.TextField()),
                ('id_opera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.opere')),
            ],
        ),
        migrations.CreateModel(
            name='Autori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
                ('data_morte', models.DateField()),
                ('vita', models.TextField()),
                ('opere', models.ManyToManyField(to='museo.opere')),
            ],
        ),
        migrations.CreateModel(
            name='Partite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
                ('terminato', models.BooleanField(default=False)),
                ('quiz', models.ManyToManyField(to='museo.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Domande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('url_pagina', models.URLField()),
                ('id_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Risposte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('isRisposta', models.BooleanField(default=False)),
                ('id_domanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museo.domande')),
            ],
        ),
    ]
